name: wakke_fwc
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_modular: any
  equatable: ^2.0.5
  dartz: ^0.10.1
  faker: ^2.0.0
  build_runner: any

  mockito: ^5.3.0
  dio: ^4.0.6
  freezed: ^2.1.0+1

  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  
  uses-material-design: true

  assets:
   - assets/
   - assets/mocks/
   - assets/mocks/success/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
