// Mocks generated by Mockito 5.3.0 from annotations
// in wakke_fwc/test/src/modules/feed/domain/usecases/get_feed_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wakke_fwc/src/modules/feed/domain/entities/feed_entity.dart'
    as _i6;
import 'package:wakke_fwc/src/modules/feed/domain/errors/errors.dart' as _i5;
import 'package:wakke_fwc/src/modules/feed/domain/repositories/feed_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [FeedRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedRepository extends _i1.Mock implements _i3.FeedRepository {
  MockFeedRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.FeedEntity>>> getFeed() =>
      (super.noSuchMethod(Invocation.method(#getFeed, []),
          returnValue:
              _i4.Future<_i2.Either<_i5.Failure, List<_i6.FeedEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.FeedEntity>>(
                      this, Invocation.method(#getFeed, [])))) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.FeedEntity>>>);
}

/// A class which mocks [FeedEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedEntity extends _i1.Mock implements _i6.FeedEntity {
  MockFeedEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get private =>
      (super.noSuchMethod(Invocation.getter(#private), returnValue: false)
          as bool);
  @override
  List<Object> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object>[])
          as List<Object>);
}
